### ISSUE TITLE
Isle of Quel'Danas: Shattered Sun quartermaster.

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#12]
"Eldara Dawnrunner" (ID 25032, DB GUID 8721) the Shattered Sun quartermaster does not open her vendor screen.
.go xyz 12890 -6873 9 530

![shatteredsunqm](https://github.com/user-attachments/assets/cf75c449-8b16-4448-a1ff-d8fc7bb12b66)

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/0c5d79b0-1c5c-488a-b372-9827cb8781a7)
I can't duplicate.

**Comment by Cayrano** [comment]
I was able to duplicate it before but it seems to be working now.
Not sure what was happening then lol.

**Comment by ghost** [comment]
Closing issue.
