### ISSUE TITLE
Shadowfang Keep: Level Scaling

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#121]
A couple NPC's do not level with the player.

Deathsworn Captain ID 3872 DB GUID 194879 
.go -234 2221 95 33
![WoWScrnShot_122024_170716](https://github.com/user-attachments/assets/c8d1958f-3c6f-43dd-962d-98cd7e35c5eb)

Lesser Gargoyle ID 3869 DB GUID 194849 
.go -218 2103 100 33
![WoWScrnShot_122024_170940](https://github.com/user-attachments/assets/df809ccf-9f54-43ec-9fcb-636f1631aeff)

**Comment by skeezerbean** [comment]
sending in an update
