### ISSUE TITLE
Arathi Highlands: Enemies without level scaling

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#124]
Some enemies in Arathi Highlands that don't have level scaling.

.go xyz -1523 -3082 15
![WoWScrnShot_122424_220901](https://github.com/user-attachments/assets/8cda40a7-663e-4d21-ad5c-b081d851e7a0)

.go xyz -2183 -1756 -61
![WoWScrnShot_122424_235701](https://github.com/user-attachments/assets/f581d910-85e4-4939-ab49-3f823eac3674)

**Comment by skeezerbean** [comment]
make sure to add the map Id in the `.go` command also

**Comment by skeezerbean** [comment]
sending in an update
