### ISSUE TITLE
Desolace: Nijel's Point Defenders

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#126]
"Nijel's Point Defender" (ID 35506, DB GUID 176353)
I think there might be too many.

.go xyz 126 1252 164 1
![WoWScrnShot_122524_022812](https://github.com/user-attachments/assets/4f0c0eb9-010c-4cd1-9e8d-02f60483794f)

.go xyz 126 1232 164 1
![WoWScrnShot_122524_022853](https://github.com/user-attachments/assets/08ccd47f-7646-46b4-a830-a3d29d78a2f8)

.go xyz 136 1326 194 1
![WoWScrnShot_122524_023108](https://github.com/user-attachments/assets/64b7cf1e-887c-4323-b3f8-6e86f1ddcbc5)

**Comment by ghost** [comment]
good greaf

**Comment by ghost** [comment]
Fixed spawning of guards. fixed some npcflags allowing gossip, and added some missing triggers for next update.
