### ISSUE TITLE
Borean Tundra: "Allies in Dalaran"

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#15]
Quest: "Allies in Dalaran" (ID 29608)
"Tomas Riverwell" (ID 26879, DB GUID 64184) does not offer a gryphon ride to Dalaran like he should.
Taxinode 245
.go xyz 2272 5171 11 571

**Comment by ghost** [comment]
Fix pushed for next update. Also added gossip for Horde flightmaster Turida Coldwind in Borean Tundra.
