### ISSUE TITLE
Moonglade: Faction Flight Masters

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#160]
The Horde and Alliance Druid flight masters are both accessible to a Horde player. They should both only be available to a Druid but should be faction specific.
Silva Fil’naveth
ID 11800
DB GUID 1059
.go xyz 7795 -2400 489 1
https://www.wowhead.com/zone=493/moonglade 
https://www.wowhead.com/classic/npc=11800/silva-filnaveth 
![WoWScrnShot_122824_214756](https://github.com/user-attachments/assets/1d9d3afc-a201-49f8-9ef1-3f6dcd78757d)
![WoWScrnShot_122824_214803](https://github.com/user-attachments/assets/2a747bbd-d78e-497a-8b12-dee48e06d1af)

**Comment by skeezerbean** [comment]
Had to check retail as some gossip was missing, and its behavior.
Yes, they should deny if you're not druid. If you are and talk to the wrong one, they tell you to talk to their counterpart now.
If you're a druid, and talk to the one for your faction, you'll get the choice to fly to Rut'theron Village or Thunder Bluff depending on your faction.
Sending in a fix in a bit for our next update.
