### ISSUE TITLE
Northern Barrens: Enemy Level Scaling

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#21]
Some NPC's in the Northern Barrens do not scale with the player.

"Rocklance" (ID 5841) https://www.wowhead.com/classic/npc=5841/rocklance 
![WoWScrnShot_121524_145542](https://github.com/user-attachments/assets/39f9c202-5a34-4147-8ee6-ef438bb7ab2c)

Quest: "Verog the Dervish" (ID 851) https://www.wowhead.com/classic/quest=851/verog-the-dervish 
"Verog the Dervish" (ID 3395) https://www.wowhead.com/classic/npc=3395/verog-the-dervish 
"Wyneth" (ID 34846) https://www.wowhead.com/npc=34846/wyneth 
![WoWScrnShot_121524_150158](https://github.com/user-attachments/assets/d569c9d8-d3a7-495b-a5b6-98f1dc3ac0b2)

"Southsea Privateer" (ID 3384) https://www.wowhead.com/npc=3384/southsea-privateer
![WoWScrnShot_121524_215040](https://github.com/user-attachments/assets/69553f21-900b-4b3a-907b-e83153da38b4)

"Gloomp" (ID 34747) https://www.wowhead.com/npc=34747/glomp
![WoWScrnShot_121524_215251](https://github.com/user-attachments/assets/4b7e373e-fd33-455a-9cac-d7da1cf26a09)

"Southsea Recruit" (ID 44168) https://www.wowhead.com/npc=44168/southsea-recruit
"Cap'n Garvey" (ID 34750) https://www.wowhead.com/npc=34750/capn-garvey
![WoWScrnShot_121524_215436](https://github.com/user-attachments/assets/4ec13ab2-32e7-48b8-bd4b-8444bbf71a85)

"Chef Toofus" (ID 34804) https://www.wowhead.com/npc=34804/chef-toofus 
![WoWScrnShot_121524_215556](https://github.com/user-attachments/assets/e19601a2-d934-4d91-87d9-f5e160a99187)

"Alicia Cuthbert" (ID 34782) https://www.wowhead.com/npc=34782/alicia-cuthbert
![WoWScrnShot_121524_215940](https://github.com/user-attachments/assets/2869fdf1-ff0d-4664-b3dc-6a5f77f3999c)

"Sludge Anomaly" (ID 3295) https://www.wowhead.com/npc=3295/sludge-anomaly
![WoWScrnShot_121524_222105](https://github.com/user-attachments/assets/fc5c1b62-7331-4ea1-8e37-7a233582bd3e)

Quest: "Sludge Beast" (ID 29089) https://www.wowhead.com/quest=29089/sludge-beast
"Sludge Beast" (ID 52165) https://www.wowhead.com/npc=52165/sludge-beast
![WoWScrnShot_121524_222218](https://github.com/user-attachments/assets/22d16a4d-e11a-4153-bc79-6392abc6609e)

"Foreman Grills" (ID 5835) https://www.wowhead.com/npc=5835/foreman-grills
![WoWScrnShot_121524_222324](https://github.com/user-attachments/assets/b2437845-7c24-4ee4-9f81-c073443982fe)

"Takk the Leaper" (ID 5842) https://www.wowhead.com/npc=5842/takk-the-leaper
![WoWScrnShot_121524_224246](https://github.com/user-attachments/assets/8fea4a7a-10d1-4cc1-ab89-4a9f8ff24566)

"Boahn" (ID 3672) https://www.wowhead.com/npc=3672/boahn
![WoWScrnShot_121724_221722](https://github.com/user-attachments/assets/b3e7c81a-a1ca-4c60-8ad4-5841c36ad596)

Quest: "Counterattack!" (ID 4021) https://www.wowhead.com/quest=4021/counterattack
"Kolkar Invader" (ID 9524) https://www.wowhead.com/npc=9524/kolkar-invader
"Warlord Krom'zar" (ID 9456) https://www.wowhead.com/npc=9456/warlord-kromzar
![WoWScrnShot_121724_211744](https://github.com/user-attachments/assets/51e53ac6-e790-4e05-88e6-f14fb5982b0b)
![WoWScrnShot_121724_211441](https://github.com/user-attachments/assets/8b394542-6e26-452a-83dc-aedaa2b072b8)

"Sunscale Ravager" (ID 44164) https://www.wowhead.com/npc=44164/sunscale-ravager
![WoWScrnShot_121524_143211](https://github.com/user-attachments/assets/43d6fd8e-41f7-4ed0-b3b2-124979058a05)

"King Reaperclaw" (ID 34829) https://www.wowhead.com/npc=34829/king-reaperclaw
![WoWScrnShot_121524_143455](https://github.com/user-attachments/assets/fcb2a6b2-1eea-4fd7-9b50-7447ade65734)

"Kurak" (ID 34635) https://www.wowhead.com/npc=34635/kurak 
![WoWScrnShot_121524_144904](https://github.com/user-attachments/assets/b5098bd0-66f9-442a-ba3f-0735ba271685)

"Lieutenant Pyre" (ID 34752) https://www.wowhead.com/npc=34752/lieutenant-pyre 
![WoWScrnShot_121524_213610](https://github.com/user-attachments/assets/7141b69f-2ec3-4ca9-9b26-3852ededf0af)

"Lieutenant Buckland" (ID 34753) https://www.wowhead.com/npc=34753/lieutenant-buckland
![WoWScrnShot_121524_213851](https://github.com/user-attachments/assets/b4ffac7c-39b0-4668-8687-8a3288363248)

**Comment by TheDdraig** [comment]
Fixed, thanks for reporting.
