### ISSUE TITLE
Northern Barrens: Ratchet Flightmaster

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#33]
Shows the Darkspear emissary message.

https://www.wowhead.com/npc=16227/bragok

![WoWScrnShot_121724_222957](https://github.com/user-attachments/assets/15fb0862-bd7a-4833-9eb1-b2c8af848bc9)

**Comment by Cayrano** [comment]
Almost every flightpath in the game shows that message for me.

**Comment by Muzantig** [comment]
Yes some do and some don't I am not sure what the rhyme or reason is.

**Comment by ghost** [comment]
Pushed gossip fix for next Update.
