### ISSUE TITLE
Mulgore: "Learn to Ride in Mulgore"

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#36]
When tracked, quest location does not appear on map. 

https://www.wowhead.com/wotlk/quest=14087/learn-to-ride-in-mulgore

![WoWScrnShot_121424_153345](https://github.com/user-attachments/assets/e6e4354e-522e-4266-801d-0a6139817ddf)

**Comment by ghost** [comment]
Fix tested and submitted for next update.
