### ISSUE TITLE
Thunder Bluff: "Gathering Leather"

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#37]
Should only be available to those with the skinning profession. 

https://www.wowhead.com/wotlk/quest=768/gathering-leather

![WoWScrnShot_121424_153833](https://github.com/user-attachments/assets/7f0b1f21-c34d-4e6c-94d5-1076b843bd79)

**Comment by ghost** [comment]
no .go xyz

**Comment by ghost** [comment]
Fix pushed for next update.
