### ISSUE TITLE
Deadmines: Quartermaster Lewis

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#38]
Quartermaster Lewis shows hostile for Horde but does not attack. I don't think he should appear at all for Horde.

https://www.wowhead.com/wotlk/npc=491/quartermaster-lewis

![WoWScrnShot_121424_163404](https://github.com/user-attachments/assets/ba9862f2-91e9-4a2c-a668-01dc72bf41f6)

**Comment by ghost** [comment]
Fix sibmitted for next update.
