### ISSUE TITLE
Ragefire Chasm: Oggleflint <Hound Food>

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#42]
Oggleflint’s corpse is full health instead of dead. 

https://www.wowhead.com/npc=61669/oggleflint

![WoWScrnShot_121424_161947](https://github.com/user-attachments/assets/62732b91-a16b-4b65-87c3-c05e172cd00f)

**Comment by ghost** [comment]
Fix submitted for next update.
