### ISSUE TITLE
Ragefire Chasm: "A New Enemy"

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#43]
You can keep collecting Corrupted Insignias after you have collected the 5 required.

https://www.wowhead.com/quest=30969/a-new-enemy
https://www.wowhead.com/item=82605/corrupted-insignia

![WoWScrnShot_121424_162152](https://github.com/user-attachments/assets/37b9db64-ea73-458b-87a4-b70710f8babf)

**Comment by TheDdraig** [comment]
Fixed, thanks for reporting
