### ISSUE TITLE
Wailing Caverns: Enemy Level Scaling

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#46]
Many enemies in the Wailing Caverns do not scale with player.

"Kresh" https://www.wowhead.com/npc=3653/kresh 
![WoWScrnShot_121724_215751](https://github.com/user-attachments/assets/82711f63-ed57-4ed3-b97b-75bee8a8fea2)

"Druid of the Fang" https://www.wowhead.com/npc=3840/druid-of-the-fang 
![WoWScrnShot_121724_215923](https://github.com/user-attachments/assets/a590dd41-7911-4a8f-aeef-201b493e4ed3)

"Deviate Adder" https://www.wowhead.com/npc=5048/deviate-adder 
![WoWScrnShot_121724_220059](https://github.com/user-attachments/assets/b8cf75ea-8c76-4d45-ab12-2194c6f3c2a3)

"Lord Cobrahn" https://www.wowhead.com/npc=3669/lord-cobrahn 
![WoWScrnShot_121724_220256](https://github.com/user-attachments/assets/c49c93f4-cf8d-4372-af82-6b288a2d3550)

"Deviate Guardian" https://www.wowhead.com/npc=3637/deviate-guardian 
![WoWScrnShot_121724_220345](https://github.com/user-attachments/assets/57163aa5-0e8a-462a-9632-656aa00d6a09)

"Deviate Crocolisk" https://www.wowhead.com/npc=5053/deviate-crocolisk
![WoWScrnShot_121724_220420](https://github.com/user-attachments/assets/48a19c6a-d68f-48df-81fd-e34a90d88188)

"Skum" https://www.wowhead.com/npc=3674/skum
![WoWScrnShot_121724_220508](https://github.com/user-attachments/assets/95a43831-64d7-435a-b6c3-14e0f367c94f)

"Deviate Shambler" https://www.wowhead.com/npc=5761/deviate-shambler
![WoWScrnShot_121724_220546](https://github.com/user-attachments/assets/d163ae65-17e0-4a24-b923-33763a4eabb7)

"Deviate Lasher" https://www.wowhead.com/npc=5055/deviate-lasher
![WoWScrnShot_121724_220645](https://github.com/user-attachments/assets/3b3b0c08-d994-4772-b3a5-8b5d5862bc4a)

"Evolving Ectoplasm" https://www.wowhead.com/npc=3640/evolving-ectoplasm 
![WoWScrnShot_121724_220710](https://github.com/user-attachments/assets/4f80d434-446d-4cff-9306-74cee83091d6)

"Deviate Faerie Dragon" https://www.wowhead.com/npc=5912/deviate-faerie-dragon 
![WoWScrnShot_121724_220739](https://github.com/user-attachments/assets/04e7097f-9b08-4d61-8a79-b1368c57545c)

"Deviate Dreadfang" https://www.wowhead.com/npc=5056/deviate-dreadfang 
![WoWScrnShot_121724_220752](https://github.com/user-attachments/assets/8ffe082f-69bf-4d13-af81-bb82c5f7c607)

"Deviate Venomwing" https://www.wowhead.com/npc=5756/deviate-venomwing 
![WoWScrnShot_121724_220852](https://github.com/user-attachments/assets/520fb83e-60f6-4b3c-a6ff-bdac7867dbad)

"Verdan the Everliving" https://www.wowhead.com/npc=5775/verdan-the-everliving 
![WoWScrnShot_121724_220918](https://github.com/user-attachments/assets/5e3e820c-a5d6-4958-bb46-5e0101253a76)

"Lord Serpentis" https://www.wowhead.com/npc=3673/lord-serpentis
![WoWScrnShot_121724_220922](https://github.com/user-attachments/assets/3c86be99-0481-4f6c-a109-bb06166a6aae)

"Mutanus the Devourer" https://www.wowhead.com/npc=3654/mutanus-the-devourer 
![WoWScrnShot_121724_221403](https://github.com/user-attachments/assets/e7f33e8b-810f-4443-bb29-0f17aa1d7cc0)

**Comment by skeezerbean** [comment]
sending in an update
