### ISSUE TITLE
Northern Barrens: Peacebloom Node

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#49]
Peacebloom node just south of Far Watch Post does not drop loot.

![WoWScrnShot_121424_221807](https://github.com/user-attachments/assets/472d0d87-6509-46d7-b065-d7438750a656)

**Comment by ghost** [comment]
Need .go xyz

**Comment by Cayrano** [comment]
> Need .go xyz

.go xyz 73 -3653 27 1

**Comment by ghost** [comment]
Fix pushed for next update.
