### ISSUE TITLE
Dalaran: Steam Powered Auctioneers

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#50]
"Brassbolt Mechawrench" and "Reginald Arcfire" appear in the same spot in the engineer shop in Dalaran.

"Brassbolt Mechawrench" (ID 35594, DB GUID 137160) (Alliance)
https://www.wowhead.com/npc=35594/brassbolt-mechawrench

"Reginald Arcfire" (ID 35607, DB GUID 370361) (Horde)
https://www.wowhead.com/npc=35607/reginald-arcfire

.go xyz 5926 728 642 571

![WoWScrnShot_121924_205802](https://github.com/user-attachments/assets/ca70ed24-f4a6-43d1-87e4-57bb17b9bcd4)

**Comment by ghost** [comment]
Fix pushed for next update.
