### ISSUE TITLE
Darkshore: "The Last Wave of Survivors"

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#67]
https://www.wowhead.com/quest=13518/the-last-wave-of-survivors
"Dentaria Silverglade" (ID 32973,  DB GUID 121481) does not give the quest "The Last Wave of Survivors" (ID 13518).
This is the first quest you get in Darkshore.
.go xyz 7449 -333 8 1

![WoWScrnShot_122024_231600](https://github.com/user-attachments/assets/35de47a2-3553-4c8a-99ef-fceea333286b)

**Comment by ghost** [comment]
Fix pushed for next update.
