### ISSUE TITLE
Hyjal: Duplicate Flightpath NPC

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#71]
"Fayran Elthas" (ID 41861, DB GUID 362774)
.go xyz 5584 -3571 1571 1
![WoWScrnShot_122124_173855](https://github.com/user-attachments/assets/60ab3da4-e658-493a-bb8c-850bc0e27d49)

**Comment by ghost** [comment]
Fixed along with issue 72.
