### ISSUE TITLE
Hyjal: Duplicate Quartermaster NPC

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#72]
"Provisioner Whitecloud" (ID 50314, DB GUID 147175)
.go xyz 5521 -3597 1571 1
![WoWScrnShot_122124_174315](https://github.com/user-attachments/assets/07acd673-e060-4422-a601-63163f99230e)

**Comment by ghost** [comment]
Lots of things wrong here. working on it.

**Comment by ghost** [comment]
fixed location of this npc and a few others. Added missing Injured Druids. Added missing portals, mailbox, anvil, and forge. Pushed  for next update.
