### ISSUE TITLE
Hyjal: "The Nordrassil Summit"

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#73]
https://www.wowhead.com/quest=29326/the-nordrassil-summit
Quest: "The Nordrassil Summit" (ID 29326)
"Thrall" (ID 54313, DB GUID 77381 + 362779) has no dialogue to continue the quest.
There also appear to be 2 Thralls, that's why i posted 2 DB GUIDs.

.go xyz 5307 -3503 1578 1
![WoWScrnShot_122124_175406](https://github.com/user-attachments/assets/2e192d1e-04b7-4ce3-aa1c-79d57bbc79e0)

**Comment by ghost** [comment]
Fix pushed for next update.
