### ISSUE TITLE
The Underbog: Incorrect creature model

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#8]
https://www.wowhead.com/npc=17734/underbog-lord
"Underbog Lord" (ID 17734, DB GUID 8797) has an incorrect model (ice giant).
.go xyz -72 -271 -2 546

![WoWScrnShot_121524_030147](https://github.com/user-attachments/assets/78c278aa-c105-4123-9cda-0470e25665df)

**Comment by ghost** [comment]
SAI added for combat and fix model issue for next release. Closing issue
