### ISSUE TITLE
Ashran: Missing Portal to Stormwind

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#81]
.go xyz 3730 -4042 45 1116
![WoWScrnShot_122224_064216](https://github.com/user-attachments/assets/65198cb2-27e6-4bd7-bcd5-f7551dc741c6)

i checked the horde side, their portal is fine
![WoWScrnShot_122224_064722](https://github.com/user-attachments/assets/cfb8a5a5-2215-473b-a2f7-1cab5307be36)

**Comment by ghost** [comment]
Stormshield is 99.9% complete now. issue fixed for next update.
