### ISSUE TITLE
Twilight Highlands: Highbank Innkeepers

### ISSUE THREAD

**Issue by Cayrano** [spp-issues/SPP-Legion-Issues#85]
Both of these Innkeepers don't allow you to bind your hearthstone.
"Innkeeper Teresa" (ID 49686, DB GUID 153667)
.go xyz -4871 -6650 11

"Innkeeper Francis" (ID 49688, DB GUID 152374)
.go xyz -4882 -6592 19

![WoWScrnShot_122224_214040](https://github.com/user-attachments/assets/2e784d92-4b4a-4f13-87d8-262b375e068c)
![WoWScrnShot_122224_214740](https://github.com/user-attachments/assets/aa2ca19c-53e4-4003-b6d8-7f214e5e67af)

**Comment by ghost** [comment]
Fix pushed for next update.
