### ISSUE TITLE
Ashenvale: NPC Level Scaling

### ISSUE THREAD

**Issue by Muzantig** [spp-issues/SPP-Legion-Issues#97]
Some NPCs that do not scale with player.

Captain Elendilad ID 33302 
![WoWScrnShot_121924_180913](https://github.com/user-attachments/assets/f9d4f613-7b03-42f9-9e15-0a6a96727bbe)

Darkslayer Mordenthal ID 3736 DB GUID 112735
![WoWScrnShot_122024_163819](https://github.com/user-attachments/assets/8113fb09-171b-4bb3-b07e-227e23ee9039)

Protector Arminon ID 34204 DB GUID 112159 .go 2444 -3275 111 1
![WoWScrnShot_122024_184919](https://github.com/user-attachments/assets/fb944e90-ba2e-4ae3-8c07-a41e808fab7f)

Protector Endolar ID 34208 DB GUID 112160 .go 2518 -3227 130 1
![WoWScrnShot_122024_185005](https://github.com/user-attachments/assets/aaa3603b-5e50-4318-9be7-945c5e28ab36)

Kaldorei Assassin ID 34206 DB GUID 201944 .go 2418 -3517 99 1 
(Kaldorei Assassin also does not fight back)
![WoWScrnShot_122024_185158](https://github.com/user-attachments/assets/2c33393b-8b46-4af9-ba8b-5f58607cce4d)

Ursangous ID 12678 DB GUID 111046 .go 2047 -712 102 1
![WoWScrnShot_122124_092451](https://github.com/user-attachments/assets/503ca3de-93d1-49ca-9b71-5c55557525c0)

Sabina Pilgrim ID 34283 DB GUID 112171 .go 2501 -1303 135 1 
(Sabina is hostile for Horde players)
![WoWScrnShot_122124_093456](https://github.com/user-attachments/assets/191db536-2f1a-453f-8beb-56b0f31dca2a)

**Comment by skeezerbean** [comment]
sending in an update for most, some already addressed in other updates
